version: '2'
services:
  exercice8-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/exercice6/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=exercice9
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
