spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        initialization-mode: always
        name: public
        password: postgres
        schema: classpath:schema-postgresql.sql
        url: jdbc:postgresql://localhost:5432/exercice8
        username: postgres
    batch:
        job:
            enabled: false
        initialize-schema: always

server:
    port: 9090